before:
  hooks:
    - go mod download
builds:
- main:
    ./cmd/s3copier/main.go
  goos:
    - linux
  env:
    - CGO_ENABLED=0
archive:
  replacements:
    linux: Linux
    amd64: x86_64
  format: zip
  files:
    - none*
